### ISSUE TITLE
How to set the lr and iteration for MINE?

### ISSUE THREAD

**Issue by yaolu-zjut** [DTennant/dt-tradeoff#1]
Would you please share the way to set the lr and iteration for mine.py? I find the lr and iteration are related to the performance of MINE. So how can i know the MINE is well optimized?

**Comment by DTennant** [comment]
Hi, Thanks for your interest in our paper.

For the lr and iter for MINE, we performed a grid search over many possible combinations of the parameters, and choose the one gives us the most stable loss curve of MINE training. (Training MINE is highly unstable)
